name: vision
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
- python=3.6.9
- pytorch=1.4.0
- torchvision=0.5.0
- cudatoolkit=10.0
- numpy=1.17.4
- pandas=0.25.3
- pillow=6.2.1
- jupyter=1.0.0
- scipy=1.3.1
- scikit-learn=0.21.3
- scikit-image=0.16.2
- tqdm=4.39.0
- pip=19.3.1
- pyyaml=5.1.2
- gitpython=3.0.5
- requests=2.22.0
- scikit-video=1.1.11
- tensorboard=1.15.0
- jupyter=1.0.0
- mpi4py=3.0.3
- networkx=2.4
- loguru=0.4.1
- python-lmdb=0.96
- moviepy=1.0.1
- visdom=0.1.8.9
- plotly=4.8.1
- opencv=4.2.0
- pip:
    - flake8==3.7.9
    - gym==0.15.7
    - pygame==1.9.6
    - yamlargparse==1.31.1
    - redlock-py==1.0.8
    - tensorboardX==2.1
    - tensorboardY==0.1.9
    - nuscenes-devkit==1.1.0
    - efficientnet-pytorch==0.7.0
    - gpustat==0.6.0
